Fix loading seed into existing create-only entity
Dropping a new moqui component usually requires loading seed using command $ gradle load.
However the process loads other seeds including those which supposed to be loaded only once into create-only entity.

To reproduce this issue/how I find this issue:
download moqui & mantel and then build and load seed 
$ gradle build
$ gradle load

download PopCommerce and put in runtime/component/PopCommerce (https://github.com/moqui/PopCommerce/archive/master.zip)
load moqui
$ gradle load

This error will appear and seems blocking the seed loading process:
25684    [           main] ERROR pl.service.ServiceCallSyncImpl  - Error running service [store#mantle.product.asset.AssetDetail]
org.moqui.entity.EntityException: Entity [mantle.product.asset.AssetDetail] is create-only (immutable), cannot be updated.
	at org.moqui.impl.entity.EntityValueBase.update(EntityValueBase.groovy:1041)

From here accessing page /popc will display subscreen error.

Work around is to clean the database and load all seeds again. 
$ gradle cleanDb
$ gradle load
Sometime this is not ideal.

Proposed amendment to fix this is on \framework\src\main\groovy\org\moqui\impl\entity\EntityValueBase.groovy, before throwing entity exception do a further check the entityValue on database. If its the entityValue same then just skip the update without raising error.